### Module 7 - Lab CountVectorizer

#### import CountVectorizer from sklearn...  nltk, and matplotlib

In [1]:
#!pip install --upgrade numpy
#!pip install --upgrade scikit-learn nltk matplotlib

# Import necessary libraries for text processing and visualization
from sklearn.feature_extraction.text import CountVectorizer
import nltk
import matplotlib.pyplot as plt

#### create an instance of the CountVectorizer class. use a variable called vectorizer

In [2]:
vectorizer = CountVectorizer()

#### use the following sample text 

In [3]:
corpus = ['NLP is about text processing', 'Text processing is necessary.', 
          'Text processing is necessary and important.', 'Text processing is easy.']

#### Call the fit() function in order to learn a vocabulary from the corpus.

In [4]:
vectorizer.fit(corpus)

,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None
,stop_words,None
,token_pattern,'(?u)\\b\\w\\w+\\b'
,ngram_range,"(1, ...)"
,analyzer,'word'


#### Let's inspect  how our vectorizer vectorized the text
#### print out a list of words used, and their index in the vectors

In [5]:
print(vectorizer.vocabulary_)

{'nlp': 6, 'is': 4, 'about': 0, 'text': 8, 'processing': 7, 'necessary': 5, 'and': 1, 'important': 3, 'easy': 2}


#### create a vector by passing the text into the vectorizer to get back counts

In [6]:
vector = vectorizer.transform(corpus)

#### display the full vector. <br> use vector.toarray()

In [7]:
print(vector.toarray())

[[1 0 0 0 1 0 1 1 1]
 [0 0 0 0 1 1 0 1 1]
 [0 1 0 1 1 1 0 1 1]
 [0 0 1 0 1 0 0 1 1]]


#### print the One Hot vector for the word: "necessary"

In [8]:
import numpy as np  # Add this import at the beginning of your code

word = "necessary"  # Replace with your desired word

if word in vectorizer.vocabulary_:
    index = vectorizer.vocabulary_[word]
    
    # Create the one-hot vector
    one_hot = np.zeros(len(vectorizer.vocabulary_))
    one_hot[index] = 1
    print("One-hot vector for 'necessary':", one_hot)
else:
    print(f"The word '{word}' is not in the vocabulary")

One-hot vector for 'necessary': [0. 0. 0. 0. 0. 1. 0. 0. 0.]


#### get the feature names

In [9]:
vectorizer.get_feature_names_out()

array(['about', 'and', 'easy', 'important', 'is', 'necessary', 'nlp',
       'processing', 'text'], dtype=object)

#### print the Frequency Distribution of the same text (corpus) using nltk.FreqDist()

In [10]:
corpus = """NLP is about text processing, Text processing is necessary., 
          Text processing is necessary and important., Text processing is easy."""

In [11]:
from nltk import FreqDist

words = corpus.lower().split()

fdist = FreqDist(words)

print("Frequency Distribution:")
for word, corpus in fdist.items():
    print(f"{word}: {corpus}")

Frequency Distribution:
nlp: 1
is: 4
about: 1
text: 4
processing,: 1
processing: 3
necessary.,: 1
necessary: 1
and: 1
important.,: 1
easy.: 1


### Part 2 - Let's use the Naive Bayes classifier

#### import pandas, os, numpy, train_test_split, CountVectorizer, accuracy_score, and MultinomialNB

In [12]:
import pandas as pd
import os
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB

### import the three text files provided: yelp_labelled.txt, amazon_cells_labelled.txt, and imdb_labelled.txt

In [13]:
import pandas as pd

filepath_dict = {'yelp':   'yelp_labelled.txt',
                 'amazon': 'amazon_cells_labelled.txt',
                 'imdb':   'imdb_labelled.txt'}

df_list = []
for source, filepath in filepath_dict.items():
    df = pd.read_csv(filepath, names=['sentence', 'label'], sep='\t')
    df['source'] = source  # Add another column filled with the source name: yelp, imdb, or amazon
    df_list.append(df)

df = pd.concat(df_list)
print(df.iloc[0])

sentence    Wow... Loved this place.
label                       positive
source                          yelp
Name: 0, dtype: object


#### display the first five records

In [14]:
df.head()

,sentence,label,source
0,Wow... Loved this place.,positive,yelp
1,Crust is not good.,negative,yelp
2,Not tasty and the texture was just nasty.,negative,yelp
3,Stopped by during the late May bank holiday of...,positive,yelp
4,The selection on the menu was great and so wer...,positive,yelp


#### display the last 10 "negative" reviews (sentences)

In [15]:
# Filter for negative reviews
negative_reviews = df[df['label'] == 'negative']

# Display the last 10 negative review sentences
print(negative_reviews['sentence'].tail(10))

720    If you act in such a film, you should be glad ...
721    This one wants to surf on the small wave of sp...
722    If you haven't choked in your own vomit by the...
725    Instead, we got a bore fest about a whiny, spo...
742              I never walked out of a movie faster.  
743    I just got bored watching Jessice Lange take h...
744    Unfortunately, any virtue in this film's produ...
745                     In a word, it is embarrassing.  
746                                 Exceptionally bad!  
747    All in all its an insult to one's intelligence...
Name: sentence, dtype: object


In [16]:
# sample
# Sample corpus and sentiment labels
corpus = [
    'NLP is about text processing',
    'Text processing is necessary.',
    'Text processing is necessary and important.',
    'Text processing is easy.',
    'This tool is frustrating.',
    'The results were disappointing.',
    'I didn’t like the output.',
    'Too many errors in the model.',
    'The predictions were inaccurate.',
    'It failed to classify correctly.',
    'Not useful at all.',
    'Terrible performance.',
    'Waste of time.',
    'Very buggy.',
    'Unreliable results.'
]

### Split the Test and Train Data into these variables: make the test size = 25% and random state = 42
### train_set, test_set, train_label, test_label

In [17]:
import numpy as np
from sklearn.model_selection import train_test_split

# Define X (features) and y (target) before using them
# For example:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])  # Replace with your actual feature data
y = np.array([0, 1, 0, 1])  # Replace with your actual target labels

# Now use train_test_split with the defined variables
train_set, test_set, train_label, test_label = train_test_split(
    X, y, test_size=0.25, random_state=42
)

#### print the number of records in the train and test sets

In [18]:
print("Number of training records:", len(train_set))
print("Number of testing records:", len(test_set))

Number of training records: 3
Number of testing records: 1


### Vectorize text data. Use the variables: countvect, x_counts, x_train_df, x_test_df

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# 1. Split into train/test
x_train, x_test, y_train, y_test = train_test_split(
    df['sentence'], df['label'], test_size=0.2, random_state=42
)

# 2. Initialize CountVectorizer
countvect = CountVectorizer()

# 3. Fit the vectorizer on training data
x_train_counts = countvect.fit_transform(x_train)

# 4. Transform the test data
x_test_counts = countvect.transform(x_test)

# 5. Create DataFrames
x_train_df = pd.DataFrame(x_train_counts.toarray(), columns=countvect.get_feature_names_out())
x_test_df  = pd.DataFrame(x_test_counts.toarray(),  columns=countvect.get_feature_names_out())

# Optional: vectorized full dataset
x_counts = countvect.fit_transform(df['sentence'])

#### print the shape of x_train_df

In [20]:
print(x_train_df.shape)

(2198, 4605)


#### Training the model

### use the Naive Bayes classifier. Use a variable called "clf" and fit the data (x_train_df,train_set.label)

In [21]:
from sklearn.naive_bayes import MultinomialNB

# Step 1: Initialize the classifier
clf = MultinomialNB()

# Step 2: Fit the model to your training data
clf.fit(x_train_counts, y_train)

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


### Test the model and print the accuracy of the Naive Bayes Classifier

In [22]:
from sklearn.metrics import accuracy_score

# Predict on the test set
predictions = clf.predict(x_test_counts)   # use the same representation as training

# Calculate accuracy
accuracy = accuracy_score(y_test, predictions)

print("Naive Bayes Classifier Accuracy:", accuracy)

Naive Bayes Classifier Accuracy: 0.7890909090909091


#### Do you believe this is a low accuracy value?

In [23]:
# If it is below 0.75, the model will overfit due to lack of diversity.

#### create a function classify_review with a parameter called text. assing countvect.transform([text]) to a variable called pred1, and return clf.predict(pred1)[0]

In [24]:
def classify_review(text):
    # your code goes here
    pred1 = countvect.transform([text])
    # end of your code
    return clf.predict(pred1)[0]

#### Test the model calling the function classify_review using the following sentences: <br> "The food was amazing !!" and "The food was awful !!"

In [25]:
print("Amazing =>", classify_review("The food was amazing !!"))

ValueError: X has 5154 features, but MultinomialNB is expecting 4605 features as input.

In [26]:
print("Awful   =>", classify_review("The food was awful !!"))

ValueError: X has 5154 features, but MultinomialNB is expecting 4605 features as input.

In [ ]:
#Kafui Tourner